default:
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      host: 10.200.207.194
      port: 1433
      user: your_username              # Replace with SQL Server login
      password: "{{ env_var('CLIENT_SQL_PASSWORD') }}"
      database: master
      schema: dbo
      encrypt: true
      trust_cert: true
  target: dev